#!/usr/bin/env bash

set -e
set -u
set -o pipefail

# Gradle can be installed system-wide as well, and setting `GRADLE_EXEC=gradle` will force
# this script to use that rather than the local wrapper.
GRADLE_EXEC="${GRADLE_EXEC:-./gradlew}"
# Gets the Git hash for `HEAD` then replaces all its characters with zero.
# When deleting a branch with git push, `local_oid` is set by Git to be
# a hash comprised entirely of zeroes. This variable gives us an accurate string to
# compare `local_oid` against.
ZERO=$(git rev-parse HEAD | tr '\[0-9a-f\]' '0')

while read -r local_ref local_oid remote_ref remote_oid; do
  # These useless assignments are to silence warnings from shellcheck about unused variables
  _=$local_ref
  _=$remote_ref
  _=$remote_oid
  if [ "${local_oid}" != "${ZERO}" ]; then
    "${GRADLE_EXEC}" check
  fi
done